In [1]:
## Importing Libraries
import requests
import pandas as pd
import time
import random
import re
import numpy as np
import _pickle as pickle
from tqdm import tqdm_notebook as tqdm
from bs4 import BeautifulSoup as bs


## Using BeautifulSoup

# Randomizing the refresh rate
seq = [i/10 for i in range(8,18)]

# Creating a list of bios
biolist = []

# Gathering bios by looping and refreshing the web page
for _ in tqdm(range(10)):
    
    # Refreshing the page
    page = requests.get("https://www.fakepersongenerator.com/user-biography-generator")
    soup = bs(page.content)
    
    try:
        # Getting the bios
        bios = soup.find('div', class_='row no-margin for-sign').find_all('p')

        # Adding to a list of the bios
        biolist.extend([re.findall('"([^"]*)"', i.text) for i in bios])
    except:
        pass
    
    # Sleeping 
    time.sleep(random.choice(seq))
    
# Creating a DF from the bio list
bio_df = pd.DataFrame(biolist, columns=['Bios'])

HBox(children=(IntProgress(value=0, max=10), HTML(value='')))

In [2]:
# List of potential Dating questions/categories
qs = ['Movies',
      'TV',
      'Religion',
      'Music',
      'Sports',
      'Books',
      'Politics']

# Creating a DF of the questions/categories
topic_df = pd.DataFrame(columns=qs)

# Filling in Data
for i in topic_df.columns:
    
    # Range of numbers to represent different labels in each category
    topic_df[i] = np.random.randint(0,10, bio_df.shape[0])
    
    # Logic: The numbers represent a specific choice within the categories
    # So your number 1 preferred artist/song/album under the Music, your one favorite movie, etc.
    
# Joining the two dataframes
final_df = bio_df.join(topic_df)
final_df

# Exporting the complete DF
with open("profiles.pkl", "wb") as fp:
    pickle.dump(final_df, fp)

In [3]:
final_df.head(10)

,Bios,Movies,TV,Religion,Music,Sports,Books,Politics
0,Freelance entrepreneur. Hardcore bacon guru. S...,0,8,1,5,4,9,9
1,Evil zombie fanatic. Award-winning social medi...,6,5,4,5,2,1,2
2,Friendly twitter trailblazer. Pop cultureaholi...,6,5,5,1,5,5,8
3,Hardcore twitter evangelist. Evil coffee junki...,4,7,6,2,7,5,1
4,Freelance music practitioner. Typical travel e...,4,0,3,4,9,6,7
5,Internet fan. Avid tv maven. Communicator. Cer...,6,0,0,0,6,3,1
6,Professional pop culture advocate. Zombie guru...,2,2,9,9,5,0,2
7,Music evangelist. Certified problem solver. Re...,5,0,7,2,2,4,7
8,Unapologetic music evangelist. Typical creator...,8,7,4,4,1,0,2
9,Professional pop culture fanatic. Hardcore cof...,2,0,1,3,1,9,0

In [4]:
final_df.shape

(150, 8)

In [5]:
bio_df.shape[0]

150

In [6]:
# List of potential Dating questions/categories
qs1 = ['Gender']

# Creating a DF of the questions/categories
topic_df1 = pd.DataFrame(columns=qs1)

# Filling in Data
for i in topic_df1.columns:
    
    # Range of numbers to represent different labels in each category
    topic_df1[i] = np.random.randint(0,2, bio_df.shape[0])    
    
    # Logic: The numbers represent a specific choice within the categories
    # So your number 1 preferred artist/song/album under the Music, your one favorite movie, etc.
    
# Joining the two dataframes
final_df1 = final_df.join(topic_df1)
final_df1

# Exporting the complete DF
with open("profiles.pkl", "wb") as fp:
    pickle.dump(final_df1, fp)

In [7]:
final_df1.head(10)

,Bios,Movies,TV,Religion,Music,Sports,Books,Politics,Gender
0,Freelance entrepreneur. Hardcore bacon guru. S...,0,8,1,5,4,9,9,0
1,Evil zombie fanatic. Award-winning social medi...,6,5,4,5,2,1,2,1
2,Friendly twitter trailblazer. Pop cultureaholi...,6,5,5,1,5,5,8,1
3,Hardcore twitter evangelist. Evil coffee junki...,4,7,6,2,7,5,1,1
4,Freelance music practitioner. Typical travel e...,4,0,3,4,9,6,7,0
5,Internet fan. Avid tv maven. Communicator. Cer...,6,0,0,0,6,3,1,1
6,Professional pop culture advocate. Zombie guru...,2,2,9,9,5,0,2,0
7,Music evangelist. Certified problem solver. Re...,5,0,7,2,2,4,7,0
8,Unapologetic music evangelist. Typical creator...,8,7,4,4,1,0,2,1
9,Professional pop culture fanatic. Hardcore cof...,2,0,1,3,1,9,0,1

In [8]:
# List of potential Dating questions/categories
qs2 = ['Age']

# Creating a DF of the questions/categories
topic_df2 = pd.DataFrame(columns=qs2)

# Filling in Data
for i in topic_df2.columns:
    
    # Range of numbers to represent different labels in each category
    topic_df2[i] = np.random.randint(15,35, bio_df.shape[0])    
    
    # Logic: The numbers represent a specific choice within the categories
    # So your number 1 preferred artist/song/album under the Music, your one favorite movie, etc.
    
# Joining the two dataframes
final_df2 = final_df1.join(topic_df2)
final_df2

# Exporting the complete DF
with open("profiles.pkl", "wb") as fp:
    pickle.dump(final_df2, fp)

In [9]:
final_df2.head(10)

,Bios,Movies,TV,Religion,Music,Sports,Books,Politics,Gender,Age
0,Freelance entrepreneur. Hardcore bacon guru. S...,0,8,1,5,4,9,9,0,16
1,Evil zombie fanatic. Award-winning social medi...,6,5,4,5,2,1,2,1,28
2,Friendly twitter trailblazer. Pop cultureaholi...,6,5,5,1,5,5,8,1,33
3,Hardcore twitter evangelist. Evil coffee junki...,4,7,6,2,7,5,1,1,20
4,Freelance music practitioner. Typical travel e...,4,0,3,4,9,6,7,0,28
5,Internet fan. Avid tv maven. Communicator. Cer...,6,0,0,0,6,3,1,1,28
6,Professional pop culture advocate. Zombie guru...,2,2,9,9,5,0,2,0,33
7,Music evangelist. Certified problem solver. Re...,5,0,7,2,2,4,7,0,19
8,Unapologetic music evangelist. Typical creator...,8,7,4,4,1,0,2,1,33
9,Professional pop culture fanatic. Hardcore cof...,2,0,1,3,1,9,0,1,22

In [10]:
final_df2.shape

(150, 10)

In [12]:
final_df2.to_csv(r'C:\Users\Prajna\Desktop\App_Synergy\data.csv', index=False)